#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意休息 任务名不是在这个文件里看 去scripts看脚本文件名字 比如duokan.js 就是duokan 4399_ylc.js就是4399_ylc
#格式报错自行百度yaml格式在线校验进去测试下就行了...
#任务列表 任务1&任务2
cbList: ssly&ssly
#是否需要推送结果 1或者不填推送 1不推送 (只推失败结果
needPush: 0
#推送参数
Push:
#企业微信推送
  qywx:
    corpsecret: 
    corpid: 
    agentid: 
    mediaid:
#telegram推送     
  tgpushkey:
    tgbotoken: 
    chatid: 
#server酱turbo版    
  sckey: 
#qmsg酱  
  qmsgkey:
#推送加  
  pushplustoken: 


#联众打码账号密码https://www.jsdati.com/
#无对应脚本 仅用于需要打码的时候
Lzong:
  account: 
  password: 


#多看阅读 cookie为app里的全部cookie
duokan:
  cookie: 
  

#橙光游戏app随便抓个包就有token
rpg66:
  uid: 
  token: 
  skey: 
  sflag: 
  folder: 
  gameid: 1569844
  did:   

#绅士领域个人uid可抓签到包看到
ssly:
  uid: 12487
  
#时光相册 手机号密码 请抓登陆包查看 手机号里包括区号 86啥的 密码为加密后的密码
everphoto:
  phone: 8611012451110
  password: 

#书香门第 登陆账号密码(只支持字母+数字组合账号)
sxmd:
  account: 
  password: 
  
#uclub这个签到失效了 在cookie里
ucloud:
  token: 
  

#好游快爆 qq 留个用于兑换qb的q scookie 去我的-赚爆米花-任务里 随便抓一个post包 请求数据里有scookie 直接分享商品链接查看  gid 和 key 分享需要兑换的商品链接查看 例https://huodong3.3839.com/n/hykb/bmhstore2/inc/libao/index.php?gid=6237 比如上面这个 gid就是6237  key就是 libao 就是查看inc/后面的那个东西 
hykb:
  scookie:  
  UA: 
  qq: 
  gid: 
  key: 

#网易蜗牛读书  都在cookie或者headers里 抓签到包最方便
du163:
  xsrf: 
  X-Auth-Token: 


  
# 香网小说网页端 全部cookie
xiang5:
  cookie:  
  

#晋江小说 手机版网页端 m.jjwxc.net cookie中sid 最好抓签到的 填完整 sid=xxx
jjwxc:
  cookie: sid=20070297_1234576798787
  sign: 

#什么值得买网页端 全部cookie
smzdm:
  cookie: 
  
#网易云游戏网页端  请求头里
cg163:
  Authorization:  
#龙空论坛 全部cookie
lkong:
  cookie: 
  
#经管之家 全部cookie
pinggu:
  cookie:  
  
#nga论坛 app端 
nga:
  uid: 
  accesstoken: 
  UA: xxxxxx Nga_Official/90306

#cdsn 网页 全部cookie
csdn:
  cookie:  
  
#mt论坛 全部cookie
mt:
  cookie: 
  time: ''

#sf轻小说 app
sfacg:
  cookie: 
  ua: 
  authorization: 

#猫耳fm 网页 全部cookie
maoer:
  cookie:  
  
  
#爱好论坛 全部cookie
aihao:
  cookie:  
  
#刺猬猫小说 
hbooker:
  token: 
  account: 
  device_token: ciweimao_
  app_version: 2.9.297

#ACFun 手机号 密码
acfun:
  phone: 
  password: 

#传奇gm论坛 全部cookie
diygm:
  cookie:  
  
#一亩三分地 登陆账号 密码 (不要设置登录问题) 联众打码平台 账号密码
ym3fd:
  username: 
  password: 
  lzusername: 
  lzpassword: 

#次元狗 全部cookie
acdog:
  cookie:  
  
#登陆联想智选app的手机号密码以及请求头header中的baseinfo
lenovo:
  account: 
  password: 
  baseinfo: 
  
#数码之家全部cookie
mydigit:
  cookie: 
  
#联动云租车 全部cookie
ldygo:
  cookie: 
  
#玩物志好物商店 如果是小程序登陆的 type 默认为wx 如果是网页的就随便改比如 web 123等等,只要不是wx就行,小程序可不填cookie,网页需要
coolbuy:
  type: wx
  authorization: 
  xcsrftoken: 
  cookie:   
  
#阅次元论坛:
abooky:
  cookie: 
  
#富贵论坛
fglt: 
  cookie: 
 
#纪录片之家
jlpzj: 
  cookie: 
  
#ug爱好者
ugsnx:
  cookie:  
  
#好书友论坛 
hsy: 
  cookie: 
  
#togamemod
togamemod: 
  cookie: 
  
#魅族社区
meizu: 
  cookie: 
 
#菜鸟图库
sucai999:
  cookie: 

#埋堆堆app
mdd: 
  appToken: 
  
#闪艺app  都在app请求post数据里  client为ios或者android gids 需要每天做刷粉丝值的作品id 用&分割 建议少于12个
shanyi:
  token: 
  u: 
  gids: 
  client: ios
  UA: 
  
  
#香蕉视频 xxx_api_auth记得加双引号
xjvideo:
  xxx_api_auth: 
  baseurl: https://7kp1t2vde8wt7p8tc0km.lagoapps.com
  
    
#有分享论坛
bl20166:
  cookie:        

#BigFun网页版  token在请求头里 x-csrf-token
bigfun:
  cookie: 
  token:   

#阡陌居
qmj: 
  cookie:     

#HiFiNi
hifini:
  cookie: 
  
#Hires后花园
dsdlove:
  cookie
            
#百度爱企查  格式变动
aiqicha: 
  cookie: 
    - cookie在这里 -不能取消 空格也要
    - 多账号继续往下 不需要的请删除

#曲奇云盘      
quqi:
  cookie:  
  
#奥拉星积分商城
aoqi:
  cookie:   
            
#4399游戏盒之疯狂游乐城 ua必填
youlecheng:
  scookie: 
  SMid: 
  device: 
  udid: 
  UA: 
  
#鱼C论坛
fishc:
  cookie: 
  
#村花论坛 hz是域名后缀 如com
cunhua: 
  cookie: 
  hz: surf

#帆软社区 脚本fanruan.js
fanruan:
  cookie: 
  
#云原神 需要在云原神里抓包x-rpc-combo_token
yunys: 
  combo_token: ai=x;ci=x;oi=xxxxxx;ct=xxxxxx;si=xxxxxx;bi=xxxxxx
  type: 
  app_version: 
  sys_version: 
  device_id: 
  device_name: 
  device_model: 
  app_id: 

#瞻彼文学 cookie为app里的全部cookie zbwx.js
zbwx: 
  cookie: accessToken=xxxxxxxx
  
#天使动漫  tsdm.js
tsdm:
  cookie:  
      
#耽漫资源网  fuman99.js
fuman99:
  cookie: 
  
#Qoo token  Qoo.js
Qoo:
  token:       

#轻之文库 linovel.js
linovel:
  username:  
  password:  
 
#游戏动力app
gamepower:
  loginCode:  
  
  
#立创
oshwhub:
  cookie: 

#捷配 客编中的数字 如 J1845A id就是1845
jiepei:
  MbId:  
#花火论坛
huahuo: 
  cookie: 

#17k小说
y7k:
  cookie:   
  
#触站
huashi6:
  cookie: 
  
#起点读书app
qidian: 
  cookie: 
  UserId: 
  deviceUid: 
  BookId: 
  TicketCount: 
  roleId: 
  version: 7.9.186
  
  
#考试宝  clientid为请求头中 client-identifier 
kaoshibao: 
  clientid: 
  authorization:   

#玩吧
wb:
  ticket: 
  deviceId: 
  nsr:     
  
#美团买菜 useid fingerprint token uuid
MeiTuan:  
  MTMC_userId: 
  MTMC_fingerprint: 
  MTMC_token: 
  MTMC_uuid: 
  
#次元姬小说
hwnovel:
  token: 