#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意冒号后边都有个空格 别删别删
#注意休息 任务名不是在这个文件里看 去scripts看脚本文件名字 比如duokan.js 就是duokan 4399_ylc.js就是4399_ylc
#格式报错自行百度yaml格式在线校验进去测试下就行了...
#任务列表 任务1&任务2
cbList: sfacg&hbooker&lenovo&qidian&smzdm
#是否需要推送结果 true全部推送  false以及不填只推送失败结果
needPush: true
#推送参数
Push:
#企业微信推送
  qywx:
    corpsecret:
    corpid:
    agentid:
    mediaid:
#telegram推送
  tgpushkey:
    tgbotoken:
    chatid:
#server酱turbo版
  sckey:
#qmsg酱
  qmsgkey:
#推送加
  pushplustoken: 322db9e4f4834325837f7a5390dc7cfa



#多看阅读 cookie为app里的全部cookie
duokan:
  cookie:

#阿里云盘
aliyun:
  refresh_token:

#星穹铁轨活动
mhy_xqtg:
  cookie:

#橙光游戏app随便抓个包就有token
rpg66:
  uid:
  token:
  skey:
  sflag:
  folder:
  gameid: 1569844
  did:

#绅士领域个人uid可抓签到包看到
ssly:
  uid: 12487

#时光相册 手机号密码 请抓登陆包查看 手机号里包括区号 86啥的 密码为加密后的密码
everphoto:
  phone: 8611012451110
  password:

#书香门第 登陆账号密码(只支持字母+数字组合账号)
sxmd:
  account:
  password:
  sxmd_host: www.txtnovel.vip

#uclub这个签到失效了 在cookie里
ucloud:
  token:


#好游快爆 qq 留个用于兑换qb的q scookie 去我的-赚爆米花-任务里 随便抓一个post包 请求数据里有scookie 直接分享商品链接查看  gid 和 key 分享需要兑换的商品链接查看 例https://huodong3.3839.com/n/hykb/bmhstore2/inc/libao/index.php?gid=6237 比如上面这个 gid就是6237  key就是 libao 就是查看inc/后面的那个东西
hykb:
  scookie: 1|0|107610508|5b+r54iG55So5oi3MTA3NjEwNTA4|kb17318F169574CB8AD768610093CC8C49|7W6xIRurIRSfIJeUGJZ0oJVnIT9r7WacpWDroR8wplI=%1|2ac757fb807c8f310b90c01c54f15098
  qq: 645934926
  gid: 14403
  key: virtual

#网易蜗牛读书  都在cookie或者headers里 抓签到包最方便
du163:
  xsrf:
  X-Auth-Token:



# 香网小说网页端 全部cookie
xiang5:
  cookie:


#晋江小说 手机版网页端 m.jjwxc.net cookie中sid 最好抓签到的 填完整 sid=xxx
jjwxc:
  cookie: sid=20070297_1234576798787
  sign:

#什么值得买网页端 全部cookie
smzdm:
  cookie: __ckguid=F8LbVtlIX7uo7SYohHpOOt6; device_id=2130706433171447324454763457ba1c3f73e5b48d706868590aa7b424; homepage_sug=d; r_sort_type=score; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1714473247,1714532830; sess=BA-1y1%2Fq7rn17Tjdu5PcyssmW%2Fw0cQ87YUE41ry%2FkCd7%2FeIRJiN8O72OkjtZVnG8xTHK8Lwkb1FL3mQg9e34PKDCMbrLE8NKE3Ksy6afW7Nf4exPHDpwCxTs%2Fyn; user=user%3A4971240378%7C4971240378; smzdm_id=4971240378; _zdmA.uid=ZDMA.5N-zsRPJn.1714532895.2419200; smzdm_user_view=CF6A730F8E0AD4A24E3DF638F6C7A3E4; smzdm_user_source=224BA94F97B058F6CF2422D8A0AEFB5E; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%224971240378%22%2C%22first_id%22%3A%2218f2e91a2fdc1-063b926499a889-26031151-1327104-18f2e91a2fec67%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E8%87%AA%E7%84%B6%E6%90%9C%E7%B4%A2%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC%22%2C%22%24latest_referrer%22%3A%22https%3A%2F%2Fwww.baidu.com%2Flink%22%7D%2C%22%24device_id%22%3A%2218f2e91a2fdc1-063b926499a889-26031151-1327104-18f2e91a2fec67%22%7D; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1714532964

#网易云游戏网页端  请求头里
cg163:
  Authorization:
#龙空论坛 全部cookie
lkong:
  cookie:

#经管之家 全部cookie
pinggu:
  cookie:

#nga论坛 app端
nga:
  uid:
  accesstoken:
  UA: xxxxxx Nga_Official/90306

#cdsn 网页 全部cookie
csdn:
  cookie:

#mt论坛 全部cookie
mt:
  cookie:
  time: ''

#sf轻小说 app
sfacg:
  cookie: .SFCommunity=0933C3E49B831C34B4FEA73C6A99FC7DB293A16447E5173B389EDB29169856A93105FCF9E7BB108ABA812DE67D0E5BBFECB9BAB8864F69AAAEC9EE22668ADCC17AC160D3DDA189C643157FF0DB7DB17C75AE02419C975BAC208B8274FB5301DE; session_PC=13861E47D13F4A482205C5A0BEBDD143;
  ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
  authorization: Basic YW5kcm9pZHVzZXI6MWEjJDUxLXl0Njk7KkFjdkBxeHE=
  
#猫耳fm 网页 全部cookie
maoer:
  cookie:


#爱好论坛 全部cookie
aihao:
  cookie:

#刺猬猫小说 book_id与reader_id用于自动投推荐票， reader_id与buy_list用于使用代币自动购买章节，buy_list格式为" [100287528,100352526,100357750] " 如不需要该功能则留空
hbooker:
  token: bc762645905dd7bcc34dba8bde9768b7
  account: 书客63756384686
  device_token: ciweimao_
  app_version: 2.9.319
  book_id:
  reader_id: 7553846
  buy_list:

#ACFun 手机号 密码
acfun:
  phone:
  password:

#传奇gm论坛 全部cookie
diygm:
  cookie:

#一亩三分地 登陆账号 密码 (不要设置登录问题) 联众打码平台 账号密码
ym3fd:
  username:
  password:
  lzusername:
  lzpassword:

#次元狗 全部cookie
acdog:
  cookie:

#登陆联想智选app的手机号密码以及请求头header中的baseinfo
lenovo:
  account: 17637011017
  password: 2015xiaoXin.
  baseinfo:

#数码之家全部cookie
mydigit:
  cookie:

#联动云租车 全部cookie
ldygo:
  cookie:

#玩物志好物商店 如果是小程序登陆的 type 默认为wx 如果是网页的就随便改比如 web 123等等,只要不是wx就行,小程序可不填cookie,网页需要
coolbuy:
  type: wx
  authorization:
  xcsrftoken:
  cookie:

#阅次元论坛:
abooky:
  cookie:

#富贵论坛
fglt:
  cookie:

#纪录片之家
jlpzj:
  cookie:

#ug爱好者
ugsnx:
  cookie:

#好书友论坛
hsy:
  cookie:

#togamemod
togamemod:
  cookie:

#魅族社区
meizu: 
  remember: 
  secret: 
  clientid: 

#菜鸟图库
sucai999:
  cookie:

#埋堆堆app
mdd:
  appToken:

#闪艺app  都在app请求post数据里  client为ios或者android gids 需要每天做刷粉丝值的作品id 用&分割 建议少于12个
shanyi:
  token:
  u:
  gids:
  client: ios
  UA:


#香蕉视频 xxx_api_auth记得加双引号
xjvideo:
  xxx_api_auth:
  baseurl: https://7kp1t2vde8wt7p8tc0km.lagoapps.com


#有分享论坛
bl20166:
  cookie:

#BigFun网页版  token在请求头里 x-csrf-token
bigfun:
  cookie:
  token:

#阡陌居
qmj:
  cookie:

#HiFiNi
hifini:
  cookie:

#Hires后花园
dsdlove:
  cookie

#百度爱企查  格式变动
aiqicha:
  cookie:
    - cookie在这里 -不能取消 空格也要
    - 多账号继续往下 不需要的请删除

#曲奇云盘
quqi:
  cookie:

#奥拉星积分商城
aoqi:
  cookie:

#4399游戏盒之疯狂游乐城 ua必填
youlecheng:
  scookie:
  SMid:
  device:
  udid:
  UA:

#鱼C论坛
fishc:
  cookie:

#村花论坛 hz是域名后缀 如com
cunhua:
  cookie:
  hz: surf

#帆软社区 脚本fanruan.js
fanruan:
  cookie:

#云原神 需要在云原神里抓包x-rpc-combo_token
yunys:
  combo_token: ai=x;ci=x;oi=xxxxxx;ct=xxxxxx;si=xxxxxx;bi=xxxxxx
  type:
  app_version:
  sys_version:
  device_id:
  device_name:
  device_model:
  app_id:

#瞻彼文学 cookie为app里的全部cookie zbwx.js
zbwx:
  cookie: accessToken=xxxxxxxx

#天使动漫  tsdm.js
tsdm:
  cookie:

#耽漫资源网  fuman99.js
fuman99:
  cookie:

#Qoo token  Qoo.js
Qoo:
  token:

#轻之文库 linovel.js
linovel:
  username:
  password:

#游戏动力app
gamepower:
  loginCode:


#立创
oshwhub:
  cookie:

#捷配 客编中的数字 如 J1845A id就是1845
jiepei:
  MbId:
#花火论坛
huahuo:
  cookie:

#17k小说
y7k:
  cookie:

#触站
huashi6:
  cookie:

#起点读书app
qidian:
  cookie: qid=888a75f81e8c110fde2140a210001a31760a; ywkey=ywnSXWXavQI2; ywguid=854016265046; appId=12; areaId=30; lang=cn; mode=normal; bar=101; cmfuToken=N((Du35kYZ4rQRHiNugjFU7wjNPZCK9y1iQkvBppcuWGjd_IIqpwFPMVVjm-0rnP2DIvAzpnlgIIzA7Rb5Gk58YHOzcdsRPEFz5QnegJYtJEqQhYHeWnJ_xwBA5oABR7ITkGftZfoMOK-05DaRc1TLT31Iyz7iqhts81VKXwF7N7s09Z4r8QFefFGtB9XHuRDt723WqaDVSYl2olhPEFjTwinF0eOJLwPOCefA9zrFILh5ctyljaOGxzEWcHiQX_SUH0nnwoeeusas1; QDInfo=X9XPsMBR1UGQZP1v+412G+twHjPkKthq0NRj+NlQUFWCdhQS3U1qOQByRytWBp8/sKY0mQ357a1t37A96k4YoaTnnWFt8AVkeXcSLvl/s7tHkzSl9MUkrjErU51RcryKK37iAUHzTIvAWkT0H2TJXL3Eb76k0jsRiywNlfyEvnp0T9hxsDjmE0jDj56kI2mNT2LRl3zUDUAmwYrNW7GbzOwxAiqbHwjzjU/vXXy4AHwFvEke3zRrdmoI7LjnJnOYkyxPC8WRcE5+pVlQF2Yy3idQ0jmMm4PZhohJO1y6w+LsuWdkAPNU404YLXYklzH8eclTrG9lu1M39bA5NK2RkA==
  UserId: 残剑飞s
  deviceUid:
  BookId:
  TicketCount:
  roleId:
  version: 7.9.341


#考试宝  clientid为请求头中 client-identifier
kaoshibao:
  clientid:
  authorization:

#玩吧
wb:
  ticket:
  deviceId:
  nsr:

#美团买菜 useid fingerprint token uuid
MeiTuan:
  MTMC_userId:
  MTMC_fingerprint:
  MTMC_token:
  MTMC_uuid:

#次元姬小说
hwnovel:
  token: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ4eW5vdmVsIiwic3ViIjoidXNlclRva2VuIiwidXNlcklkIjoiMjAzMDMxNzEzODc2NDgyNDQ2In0.5XI-XtqiQgsaZ2yAnodAvQL7OvL7jrkuSIGQfHkBqKg

# Anime字幕论坛
Anime:
  cookie:

# 黑丝次元
hscy:
  authorization:
# 克拉漫播
kilamanbo:
  authtoken: 
  ua: 

#库街区
kurobbs:
  token:
  devCode:

# linkai
linkai:
  Authorization:

# 泡芙加速器
pfjsq:
  token:

# 海贼王论坛
hzw:
  cookie:
  formhash:
  
# 共创世界
ccw: 
  token: 

# 科研通  
ablesci:
  cookie:   

# 月影别墅
simba: 
  refreshtoken:  

# pdg2pdf
pdg2pdf: 
  cookie:  

# 高清mp4 
mp4fan: 
  cookie:   

# Go柄(Gobing)
gobing: 
  account: 
  password: 
